apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ztxy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0046-tenant/tkrw-pr714-0075-0046-app/devfile-sample-ztxy@sha256:5073cd7089ef41661ea5f5321845fbefe66f4bc88ae4676ef4bb4b0ce326ab84
        name: my-nodejs
        resources: {}
status: {}
