apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ztxy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ztxy
    app.kubernetes.io/part-of: tkrw-pr714-0075-0046-app
  name: devfile-sample-ztxy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ztxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ztxy
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0046-tenant/tkrw-pr714-0075-0046-app/devfile-sample-ztxy@sha256:5073cd7089ef41661ea5f5321845fbefe66f4bc88ae4676ef4bb4b0ce326ab84
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
